# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1203, 779)
        MainWindow.setMinimumSize(QtCore.QSize(1203, 779))
        MainWindow.setMaximumSize(QtCore.QSize(1203, 779))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(9, 10, 1181, 311))
        self.groupBox.setObjectName("groupBox")
        self.logTextEdit = QtWidgets.QTextEdit(self.groupBox)
        self.logTextEdit.setGeometry(QtCore.QRect(13, 26, 961, 271))
        self.logTextEdit.setObjectName("logTextEdit")
        self.startButton = QtWidgets.QPushButton(self.groupBox)
        self.startButton.setGeometry(QtCore.QRect(990, 30, 171, 81))
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(self.groupBox)
        self.stopButton.setGeometry(QtCore.QRect(990, 180, 171, 81))
        self.stopButton.setObjectName("stopButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(9, 330, 1181, 391))
        self.groupBox_2.setObjectName("groupBox_2")
        self.createButton = QtWidgets.QPushButton(self.groupBox_2)
        self.createButton.setGeometry(QtCore.QRect(990, 40, 171, 81))
        self.createButton.setObjectName("createButton")
        self.editButton = QtWidgets.QPushButton(self.groupBox_2)
        self.editButton.setGeometry(QtCore.QRect(990, 160, 171, 81))
        self.editButton.setObjectName("editButton")
        self.deleteButton = QtWidgets.QPushButton(self.groupBox_2)
        self.deleteButton.setGeometry(QtCore.QRect(990, 280, 171, 81))
        self.deleteButton.setObjectName("deleteButton")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setGeometry(QtCore.QRect(15, 21, 961, 361))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1203, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Logs"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.groupBox_2.setTitle(_translate("MainWindow", "User"))
        self.createButton.setText(_translate("MainWindow", "Create"))
        self.editButton.setText(_translate("MainWindow", "Edit"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
